---
deployment:
  tasks:
    - export DEPLOYPATH=/home/wipbolivia/public_html
    - /bin/mkdir -p $DEPLOYPATH/wip-new
    - /bin/cp -R -f sitio-web-actual/wip-new/. $DEPLOYPATH/wip-new/
    - /bin/cp -R -f sitio-web-actual/wip-new/. $DEPLOYPATH/
